# Generated by Django 3.0.2 on 2020-03-15 16:56

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        HStoreExtension(),
    ]

