site_name: indicators-api
repo_url: https://github.com/mdauner/indicators-api
copyright: Copyright &copy; 2019, <a href="https://github.com/mdauner">mdauner</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - DataSets: 'api/datasets.md'
